"""empty message

Revision ID: 8e462ff0f71f
Revises: 5159e1ddc086
Create Date: 2017-10-21 19:54:15.069182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e462ff0f71f'
down_revision = '5159e1ddc086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'about_me')
    op.drop_column('post', 'disabled')
    # ### end Alembic commands ###
