"""empty message

Revision ID: 9ff79fa1d156
Revises: f2dc1ed5c635
Create Date: 2017-11-09 15:11:20.128902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff79fa1d156'
down_revision = 'f2dc1ed5c635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift', sa.Column('tag', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift', 'tag')
    # ### end Alembic commands ###
